AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

Resources:

  ## KINESIS SOURCE STREAM FOR Radd Change Data Capture
  RaddCdcKinesis:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-stream.yaml"
      Parameters:
        StreamName: !Sub '${ProjectName}-radd-fsu-cdc-stream'
        StreamRetentionPeriodHours: 24

  RaddTransactionDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-radd-transaction'
      AttributeDefinitions:
        - AttributeName: "operationId"
          AttributeType: "S"
        - AttributeName: "iun"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "operationId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5" 
      GlobalSecondaryIndexes:
        -
          IndexName: "iun-global"
          KeySchema:
            -
              AttributeName: "iun"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      KinesisStreamSpecification:
        StreamArn: !GetAtt RaddCdcKinesis.Outputs.KinesisStreamArn
      StreamSpecification: 
        StreamViewType: NEW_IMAGE

Outputs:
  RaddTransactionDynamoTable:
    Description: Name of dynamodb table containing radd transaction
    Value: !Ref RaddTransactionDynamoTable
  RaddTransactionDynamoTableArn:
    Description: ARN of dynamodb table containing transaction
    Value: !Sub '${RaddTransactionDynamoTable.Arn}'
