AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'

  AlarmSNSTopicName:
    Type: String

Resources:

  RaddTransactionDynamoTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TableName: !Sub '${ProjectName}-radd-transaction-alt'
      AttributeDefinitions:
        - AttributeName: "transactionId"
          AttributeType: "S"
        - AttributeName: "operationType"
          AttributeType: "S"
        - AttributeName: "iun"
          AttributeType: "S"
        - AttributeName: "recipientId"
          AttributeType: "S"
        - AttributeName: "delegateId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "transactionId"
          KeyType: "HASH"
        - AttributeName: "operationType"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "iun-transaction-index"
          KeySchema:
            - AttributeName: "iun"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "recipient-transaction-index"
          KeySchema:
            - AttributeName: "recipientId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "delegate-transaction-index"
          KeySchema:
            - AttributeName: "delegateId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"      
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification: 
        StreamViewType: NEW_IMAGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  OperationsDynamoTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TableName: !Sub '${ProjectName}-operations-iuns-alt'
      AttributeDefinitions:
        - AttributeName: "transactionId"
          AttributeType: "S"
        - AttributeName: "iun"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "transactionId"
          KeyType: "HASH"
        - AttributeName: "iun"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "iun-transaction-index"
          KeySchema:
            - AttributeName: "iun"
              KeyType: "HASH"
            - AttributeName: "transactionId"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"      
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  RaddRegistryRequestDynamoTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-RaddRegistryRequest'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "cxId"
          AttributeType: "S"
        - AttributeName: "requestId"
          AttributeType: "S"
        - AttributeName: "correlationId"
          AttributeType: "S"
        - AttributeName: "registryId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "cxId-requestId-index"
          KeySchema:
            - AttributeName: "cxId"
              KeyType: "HASH"
            - AttributeName: "requestId"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "correlationId-index"
          KeySchema:
            - AttributeName: "correlationId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "cxId-registryId-index"
          KeySchema:
            - AttributeName: "cxId"
              KeyType: "HASH"
            - AttributeName: "registryId"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true


  RaddRegistryImportDynamoTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-RaddRegistryImport'
      AttributeDefinitions:
        - AttributeName: "cxId"
          AttributeType: "S"
        - AttributeName: "requestId"
          AttributeType: "S"
        - AttributeName: "fileKey"
          AttributeType: "S"
        - AttributeName: "status"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "cxId"
          KeyType: "HASH"
        - AttributeName: "requestId"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "fileKey-index"
          KeySchema:
            - AttributeName: "fileKey"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "status-index"
          KeySchema:
            - AttributeName: "status"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      BillingMode: "PAY_PER_REQUEST"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true


  RaddRegistryDynamoTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-RaddRegistry'
      AttributeDefinitions:
        - AttributeName: "registryId"
          AttributeType: "S"
        - AttributeName: "cxId"
          AttributeType: "S"
        - AttributeName: "requestId"
          AttributeType: "S"
        - AttributeName: "zipCode"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "registryId"
          KeyType: "HASH"
        - AttributeName: "cxId"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "cxId-requestId-index"
          KeySchema:
            - AttributeName: "cxId"
              KeyType: "HASH"
            - AttributeName: "requestId"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "zipCode-index"
          KeySchema:
            - AttributeName: "zipCode"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true


  # Coda per interna per valutazione cap
  # NB: usati i valori di default per: DeadLetterQueueName, MessageRetentionPeriod, DeadLetterMessageRetentionPeriod
  RaddInternalCapCheckerQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-radd_alt_internal_cap_checker'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 60
        MaxReceiveCount: 10
        DelaySeconds: 1

  RaddAltStoreLocatorQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-radd-alt-store-locator'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 60
        MaxReceiveCount: 10
        DelaySeconds: 1

  RaddLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-radd-alt'
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn

  # Coda interna per costruzione evento da inviare ad address manager
  # NB: usati i valori di default per: DeadLetterQueueName, MessageRetentionPeriod, DeadLetterMessageRetentionPeriod
  PnRaddAltInputQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-radd_alt_input'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 180
        MaxReceiveCount: 10
        DelaySeconds: 1

  # Shared lock handling table
  ShedLockTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-RaddShedLock'
      AttributeDefinitions:
        - AttributeName: "_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "_id"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

Outputs:
  RaddTransactionDynamoTableName:
    Description: Name of dynamodb table containing radd transaction
    Value: !Ref RaddTransactionDynamoTable

  OperationsDynamoTableName:
    Description: Name of dynamodb table containing iuns and operations
    Value: !Ref OperationsDynamoTable

  RaddRegistryImportDynamoTableName:
    Description: Name of dynamodb table containing anagrafiche
    Value: !Ref RaddRegistryImportDynamoTable

  RaddTransactionDynamoTableArn:
    Description: ARN of dynamodb table containing transaction
    Value: !Sub '${RaddTransactionDynamoTable.Arn}'

  OperationsDynamoTableArn:
    Description: ARN of dynamodb table containing iuns and operations
    Value: !Sub '${OperationsDynamoTable.Arn}'

  RaddRegistryImportDynamoTableArn:
    Description: Name of dynamodb table containing anagrafiche
    Value: !Sub '${RaddRegistryImportDynamoTable.Arn}'

  RaddRegistryRequestDynamoTableName:
    Description: Name of dynamodb table containing requests
    Value: !Ref RaddRegistryRequestDynamoTable

  RaddRegistryRequestDynamoTableArn:
    Description: ARN of dynamodb table containing requests
    Value: !Sub '${RaddRegistryRequestDynamoTable.Arn}'

  RaddRegistryDynamoTableName:
    Description: Name of dynamodb table containing radd registry
    Value: !Ref RaddRegistryDynamoTable

  RaddRegistryDynamoTableArn:
    Description: ARN of dynamodb table containing radd registry
    Value: !Sub '${RaddRegistryDynamoTable.Arn}'

  # RaddInternalCapCheckerQueue Queue
  RaddInternalCapCheckerQueueName:
    Value: !GetAtt RaddInternalCapCheckerQueue.Outputs.QueueName
  RaddInternalCapCheckerQueueARN:
    Value: !GetAtt RaddInternalCapCheckerQueue.Outputs.QueueARN
  RaddInternalCapCheckerDLQName:
    Value: !GetAtt RaddInternalCapCheckerQueue.Outputs.DeadLetterQueueName
  RaddInternalCapCheckerDLQARN:
    Value: !GetAtt RaddInternalCapCheckerQueue.Outputs.DeadLetterQueueARN

  # RaddAltStoreLocatorQueue Queue
  RaddAltStoreLocatorQueueName:
    Value: !GetAtt RaddAltStoreLocatorQueue.Outputs.QueueName
  RaddAltStoreLocatorQueueARN:
    Value: !GetAtt RaddAltStoreLocatorQueue.Outputs.QueueARN
  RaddAltStoreLocatorDLQName:
    Value: !GetAtt RaddAltStoreLocatorQueue.Outputs.DeadLetterQueueName
  RaddAltStoreLocatorDLQARN:
    Value: !GetAtt RaddAltStoreLocatorQueue.Outputs.DeadLetterQueueARN

  # Log group exports
  EcsLogGroup:
    Value: !GetAtt RaddLogGroup.Outputs.LogGroupName

  # PnRaddAltInputQueue Queue
  PnRaddAltInputQueueName:
    Value: !GetAtt PnRaddAltInputQueue.Outputs.QueueName
  PnRaddAltInputQueueARN:
    Value: !GetAtt PnRaddAltInputQueue.Outputs.QueueARN
  PnRaddAltInputQueueDLQName:
    Value: !GetAtt PnRaddAltInputQueue.Outputs.DeadLetterQueueName
  PnRaddAltInputQueueDLQARN:
    Value: !GetAtt PnRaddAltInputQueue.Outputs.DeadLetterQueueARN

  ShedLockTableName:
    Value: !Ref ShedLockTable
  ShedLockTableArn:
    Value: !Sub '${ShedLockTable.Arn}'